version: "3.9"

services:
  db:
    image: postgres:12.1
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: django_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    env_file:
      - environment.env

  django:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:4545
    container_name: django
    volumes:
      - .:/code
    ports:
      - "4545:4545"
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
